### ISSUE TITLE
Randomly cannot use or target any usable objects in mouse mode

### ISSUE THREAD

**Issue by Daist** [axjv/Input-Switcher#16]
Hello. First releases were great, but around 3-5 days ago I noticed I cannot target monsters from time to time (the sword icon just doesn't appear) or use the teleport statue with Cooldown Tracker installed. Unistalled it, restarted the game - everything works flawlessly again. Feels like there is some overlay over objects and I cannot interact with them. However, I read somewhere in the forums that one of the recent game updates broke mouse controls. Which one is the problem, what do you think?

**Comment by axjv** [comment]
I do believe there is a problem with mouse mode currently. Sometimes it works, sometimes it doesn't. I can tell you that cdtracker doesn't draw anything besides the skill and buff windows on the screen, and when /cd lock is on nothing from the addon should get in the way of your mouse. Or rather, everything is changed so that the mouse will go through.

I am also experiencing the same problem, and even disabling all addons it still happens.

**Comment by Daist** [comment]
So I guess we'll just have to wait for a fix from IMC to be able to use cooldown tracker again.
By the way, I wanted to ask this for a long time, can you make an addon that would count down 10 seconds from the last hp/sp regen tick and display an icon signalling about it? Sitting down and getting up every 10 seconds for faster regen saves so many pots, but it's kinda hard to keep track of 10 seconds every time...

**Comment by axjv** [comment]
I've attempted to implement a temporary workaround for this problem. The cursor will reset itself every skill use. Hopefully this will cause the bug to appear less frequently.

Let me know if you still have problems, and in what situations.

**Comment by Daist** [comment]
Thanks a lot, I'll try it asap!

**Comment by Daist** [comment]
Nope, it's still happening, and immediately after I installed this addon :( Made a video, will upload it, maybe you can figure out in what circumstances this happens.
Settings.json:

{"skillPosX":829,"buffPosY":150,"buffPosX":250,"chatList":[],"ignoreList":[],"lock":false,"sound":true,"firstTimeMessage":true,"checkVal":5,"text":true,"message":[],"soundtype":1,"skin":1,"skills":true,"skillPosY":62,"buffs":false,"alerts":true,"size":1}

Video: https://youtu.be/w967kU6-wEY (probably still low-res at the moment) - cannot attack at around 0:30, the cursor just didn't turn into a sword, only showed a regular arrow (too bad video capture doesn't show the cursor).

**Comment by slowmelodic** [comment]
Is it possible for you to make the yellow chat only cd tracker, thats the most important thing to have as a support char, and i do feel like there is overlay over the objects and its randomly moving from middle, right, left, top and bottom of the screen from time to time in the full version cd tracker. Uninstalled, all back to normal and when installed its occured again. Disabling it seems only hide the tracker but the overlay still exist. Thanks in advance.

**Comment by axjv** [comment]
Try the newest version and let me know if you still have problems.

**Comment by Daist** [comment]
Still happened during boss fight in a mission. Alas, have to uninstall. Thanks anyway.
Tried the next day, feels like a random part of the screen is covered by some overlay every now and then, making it impossible to play normally.

**Comment by Narthorn** [comment]
To reproduce: Entering rest mode immediately creates an invisible, non-clickthrough 500x500px frame named 'cdtracker' in the middle of the screen. This frame can be dragged around (even with /cd lock active), making it feel like the area where the mouse is blocked is random.

**Comment by Daist** [comment]
> Entering rest mode immediately creates an invisible, non-clickthrough 500x500px frame

Maybe this is the cause, I use rest very often to regen SP faster.

**Comment by axjv** [comment]
This issue should be resolved now. It seems there was a problem with the xml configuration that caused it to spawn a frame that obstructs clicking. The 'Rest' buff appears to be the culprit. CDTracker uses multiple frames to display information, but all are modified versions of the default frame, which is set as a 500x500 draggable frame in the middle of the screen. The 'Rest' buff frame in particular remained as the default, causing the mouse mode problems.

I've resized the default frame to 0px so that this should no longer happen. In the future I will add support for a blacklist of buffs, which by default will include things like Rest, Team Level and Token.

**Comment by Daist** [comment]
Great news, thanks! Seems to work fine now, only was unable to attack once today, probably the game's own bug now.
