### ISSUE TITLE
Bug Insta casting skills

### ISSUE THREAD

**Issue by darksady** [axjv/Input-Switcher#26]
I dont know what exactly i did, but sometimes the addon remove the cast from sleep, meteor, i dont have many information about this but i hope u check this.

**Comment by s1lv3rw0lf** [comment]
I got the same problem on Chortasmata.

When did this bug started for you. And under what situation?

**Comment by darksady** [comment]
The bug started when i was on pvp, i had just installed it and config some skill times.Im trying to discovery something that might bug my skills.But i know for sure it's because of cdtracker.

**Comment by parazito** [comment]
To make this bug happen you need to change the value field "time" (below of individual skills). 
To make the bug disappear you need to restart tos. Sometimes your client will crash too.
It's pretty damn op if you use on team battle. You can rush at enemy team and drop your meteor or rune of destruction.
I've sent a ticket to imc and their response was to uninstall the addon while they fix the problem. If you being caught using this addon you should be banned or the account restricted. 
The author of this addon must to fix this problem too because it is exploiting the cast time even intended or not.

**Comment by axjv** [comment]
Please record a video if you can reproduce this bug, I can't get this to happen after testing for a few hours on multiple characters.

Also post the contents of your settings.json file located in addons/cdtracker.

**Comment by parazito** [comment]
Video: https://youtu.be/4m3mt4j_GqM
[settings - Cópia.json.txt](https://github.com/axjv/Input-Switcher/files/415548/settings.-.Copia.json.txt)

**Comment by s1lv3rw0lf** [comment]
https://www.youtube.com/watch?v=IXOkCFdCuo0

Here its how i reproduce it.

Description:

Open CDtracker UI, turn on or off the chat checkbox.

Close it

Try to cast an aimed skill: It will autocast. The position for my chortasmata was off from my mouse (where i casted heal) And it will keep casting on the same place. 

Content for settings.json

`{"skillPosX":876,"buffPosY":95,"buffPosX":389,"chatList":{"[Skill] Enchant Fire":true,"[Skill] Carve Vakarine":true,"[Skill] Heal":false,"[Skill] Carnivory":false,"[Skill] Safety Zone":false,"[Skill] Carve Ausirine":true,"[Skill] Carve Owl":false,"[Skill] Samsara":true,"[Skill] Joint Penalty":true,"[Skill] Carve":false},"ignoreList":{"[Buff] Rest":true,"[Skill] Carve Ausirine":false,"[Buff] Divine Might":false,"[Skill] Heal":false,"[Buff] Field Boss Cube Unobtainable":true,"[Buff] Heal":true,"[Buff] Cure":true,"[Buff] HP Aura":true,"[Buff] Team Level":true,"[Buff] Statue of Goddess Laima":true,"[Buff] Increased party EXP rate for Instanced Dungeons":true,"[Skill] Safety Zone":false,"[Buff] Statue of Goddess Zemyna":true,"[Buff] Token":true,"[Skill] Carve":false},"skin":6,"sound":false,"soundtype":1,"checkVal":0,"text":false,"lock":true,"firstTimeMessage":true,"message":{"[Skill] Carve Vakarine":"FREE WARP (ignore silver price)","[Skill] Carve Ausirine":"Ausrine HERE!!"},"buffs":true,"chattype":2,"time":{"[Skill] Carve Ausirine":0},"skillPosY":206,"skills":false,"alerts":true,"size":0.85}`

**Comment by axjv** [comment]
Update to version 3.0.4 and let me know if this issue still exists.

**Comment by FiftyCaliber** [comment]
New issue with 3.0.4? It prevents me from using any consumables on my quickslots.
- Installed v3.0.4 via Addon Manager
- Ran Tree of Savior and logged on my Cryokino.
- Immediately upon logging in I can't use any consumables on quickslots.
- Restart Client...
- Issue is still occurring, I CAN use consumables directly from my inventory.
- Uninstall CD Tracker
- Ran Tree of Savior again and the issue is gone.

**Comment by axjv** [comment]
Version 3.0.5 should fix the issue, my code will now only run on the hotbar slots that have skills in them.
