### ISSUE TITLE
Game crash while using /inputswitch toggle command

### ISSUE THREAD

**Issue by Lazarus-Slate** [axjv/Input-Switcher#4]
The game crashes occasionally when using the /inputswitch toggle command:
http://screencast.com/t/iavWwMzNS5VT
It can not be reproduced all the time but it seems that it happens when you use the /inputswitch toggle command several times within a short period of time.

**Comment by axjv** [comment]
Updated, see if that helps.

**Comment by Lazarus-Slate** [comment]
Seems to be more stable  (I was able to switch more often before the game crashed) now but the issue still persists. If you use the /inputswitch toggle command several times within a short period of time, the game still crashes:
http://screencast.com/t/mZYVolyQt2Q

**Comment by axjv** [comment]
There should be a text file that opens up when the game crashes, can you paste that here?

You might want to try uninstalling and then reinstalling the addon, there's not much I can do to change the code, because typing /inputswitch toggle only runs 1 line of code that changes a value in the settings file.

**Comment by Lazarus-Slate** [comment]
I uninstalled and reinstalled Input-Switcher but the issues still persists.

The only crash related file I could find is named Crash.rep but opening it with the editor only shows many cryptic stuff. Maybe it helps anyway. Unfortunately I was not able to attach it here as the file type is not supported. If you meant a different file, please let me know where I can find it, so that I can provide it.

**Comment by axjv** [comment]
Every time the game crashes it writes a text file telling what caused the crash. This file usually is opened automatically when you crash, but if it doesn't it should be located in TreeOfSavior/release, the filename should start with ExtraDump_Client_tos. Copy what's in the newest file here and I'll take a look.

**Comment by Lazarus-Slate** [comment]
I found the file and attached it here. Hopefully it is helpful.
[StackDump_Client_tos[06.26 06h09m33s].txt](https://github.com/axjv/Input-Switcher/files/333426/StackDump_Client_tos.06.26.06h09m33s.txt)

**Comment by axjv** [comment]
Can you try turning off Steam Overlay and Desktop Game Theatre? You can find these settings in your Steam Library window, right click on Tree of Savior in the left pane, and click properties. Uncheck both boxes, and let me know if you still have problems.

**Comment by Lazarus-Slate** [comment]
I tried you recommendations but it seems not to change anything. After using a couple of times the /inputswitch toggle command, the game crashed again.

Just to be sure, you meant these settings/check boxes unchecked, right?
http://screencast.com/t/xtD9gxjCrsL

Sorry for German Steam client but I guess the options basically are the same.

**Comment by axjv** [comment]
Okay, from reading the error log it seems that the client is having trouble accessing memory. This is usually caused by a problem with your game files. First thing you should try is going to the properties window again, and go to the tab labeled 'LOKALE DATEEN'. There should be 4 options there, the last one is to verify your game files. Choose that one, and Steam will try to automatically fix any errors in your files.

After looking at older crash reports from users with the same error as yours, it seems that their Steam was also in German. I'm not completely sure, but if verifying the game files still doesn't work, try setting the language to English.

If none of that works, I'm afraid the only solution I can offer is to reinstall the game.

The code for input switcher is very short, and nothing in it should cause client crashes. It modifies the same file that the ingame settings access, and simply changes a number from 2 to 3. There isn't much I can change about the code because it is so short. The last update I made removed any extra code that could possibly cause crashes.

So, I hope that one of the above solutions works for you. If not, then I apologize for not being able to help.

**Comment by Lazarus-Slate** [comment]
Unfortunately nothing really worked. I ran the steam repair and it actually did request new files which afterwards the IMC installer provided but the issue was still present.

Moreover I changed the Steam language to English but the game crashed again after using a couple of times the /inputswitch toggle command.

I guess it is a quite specific issue which maybe has something to to with my PC/software configuration or something alike. But I guess I'll never find out ... maybe in the future by accident.

Thank you anyway for all your tips and taking time to further investigate the issue. For now I will uninstall the addon again as it is not useful for me when it crashes my game.
